{"uuid": "646b30d7-8be1-4690-9154-a7e28387dbee", "children": ["a95019af-dcc3-40bc-bf8a-e631d44e8a9e"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1686634680936, "stop": 1686634680936}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/home/vipul/.local/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/vipul/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"/home/vipul/PageObjectModel/TestCases/conftest.py\", line 38, in log_on_failure\n    if item.rep_call.failed:\n"}, "start": 1686634685223, "stop": 1686634685223}], "start": 1686634680936, "stop": 1686634685223}